### Get a list of all tournaments
GET {{url}}:{{port}}/api/tournaments/

### Get all tournaments with a specific name
GET {{url}}:{{port}}/api/tournaments/Elfmeterturnier

### Create a new tournament
POST {{url}}:{{port}}/api/tournaments/
Content-Type: application/json

{
  "name": "Champions Cup",
  "startDate": "2025-07-01T10:00:00Z",
  "endDate": "2025-07-10T18:00:00Z",
  "location": {
    "city": "Berlin",
    "venue": "Olympiastadion"
  },
  "winner": {
    "name": "Team A",
    "coach": "Coach X"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(response)
        client.assert(response.status === 200);
    });

    client.test("Check tournament name", function () {
        const body = response.body;
        client.assert(body.name === "Champions Cup");
    });
%}

### Update existing tournament
PUT {{url}}:{{port}}/api/tournaments/1
Content-Type: application/json

{
  "name": "Champions Cup - Final",
  "startDate": "2025-07-01T10:00:00Z",
  "endDate": "2025-07-12T20:00:00Z",
  "location": {
    "city": "Berlin",
    "venue": "Olympiastadion"
  },
  "winner": {
    "name": "Team B",
    "coach": "Coach Y"
  }
}

### Delete existing tournament
DELETE {{url}}:{{port}}/api/tournaments/delete/1
