name: Build Maven Project

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Build with Maven
        run: mvn clean install

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: target/*.jar
